<a href="https://colab.research.google.com/github/Mishazam/Initial_Deep_Learning/blob/Initial-Tensor-Flow/InitialMZA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.14808546, -0.1297324 ,  0.02414397,  0.30298454,  0.47909075,
        -0.18334104,  0.5936002 , -0.14602086,  0.17775795,  0.15824369]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.07429805, 0.07567423, 0.08826239, 0.11664728, 0.13910943,
        0.07172427, 0.15598664, 0.0744516 , 0.10291754, 0.10092865]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

<LossFunctionWrapper(<function sparse_categorical_crossentropy at 0x7a1415ee6ac0>, kwargs={'from_logits': True, 'ignore_class': None})>

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.634926)

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9804 - loss: 0.0602
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9826 - loss: 0.0516
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9830 - loss: 0.0487
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - accuracy: 0.9856 - loss: 0.0452
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9874 - loss: 0.0393
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9878 - loss: 0.0376
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9883 - loss: 0.0341
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9886 - loss: 0.0332
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9888 - loss: 0.0327
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9904 - loss: 0.0287


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9803 - loss: 0.0740


[0.07404197752475739, 0.9803000092506409]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.89119514e-10, 9.35568287e-14, 2.18664309e-09, 1.03514503e-06,
        9.58923564e-16, 2.30226643e-10, 1.32456738e-20, 9.99998689e-01,
        1.04471045e-08, 1.88144284e-07],
       [2.49193366e-15, 1.90809942e-07, 9.99999762e-01, 1.25418707e-08,
        1.76202881e-25, 5.37581091e-11, 7.97516892e-13, 1.30564875e-16,
        4.17800430e-12, 8.11351882e-24],
       [6.32742192e-10, 9.99978662e-01, 4.21299865e-06, 1.44449128e-08,
        6.59307943e-07, 1.66361112e-08, 3.11694599e-08, 9.19312333e-06,
        7.30117699e-06, 7.98362348e-11],
       [9.99992847e-01, 8.32069168e-13, 2.74363174e-06, 2.19145993e-10,
        6.53654377e-13, 1.90303149e-06, 2.14297484e-06, 3.34427995e-07,
        5.77026220e-13, 4.45767245e-09],
       [3.05758263e-08, 2.00516138e-16, 4.80639839e-09, 2.85417252e-13,
        9.99680161e-01, 3.81696888e-12, 2.19812684e-08, 2.02544038e-06,
        1.21255972e-09, 3.17879807e-04]], dtype=float32)>